inherit SKILL;

mapping *quest = ({
        ([      "quest":                "¿œƒÍ…Ã»À",
                "quest_type":           "…±",
                "time":                 600,
                "exp_bonus":         100,
                "pot_bonus":          30,
                "score" :               5
        ]),
     ([      "quest":                "∫˙µ∂",
                "quest_type":           "—∞",
                "time":                 800,
                "exp_bonus":       100,
                "pot_bonus":         30,
                "score" :               5
        ]),
    ([      "quest":                "ƒÍ«·…Ã»À",
                "quest_type":           "…±",
                "time":                 800,
                "exp_bonus":         100,
                "pot_bonus":           30,
                "score" :               5
        ]),
   ([      "quest":                "—Ú∆§æ∆¥¸",
                "quest_type":           "—∞",
                "time":                 800,
                "exp_bonus":         100,
                "pot_bonus":            20,
                "score" :               5
        ]),
        ([      "quest":                "≥§∞◊ª¢",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":         200,
                "pot_bonus":           30,
                "score" :               20
        ]),
     ([      "quest":                "∫⁄…´…Æ≈€",
                "quest_type":          "—∞",
                "time":                 800,
                "exp_bonus":       80,
                "pot_bonus":         20,
                "score" :               5
        ]),
      ([      "quest":                "≈Æ∆Õ",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":            30,
                "pot_bonus":           10,
                "score" :               5
        ]),
         ([      "quest":                "—æ˜ﬂ",
                "quest_type":           "…±",
                "time":                 100,
                "exp_bonus":          30,
                "pot_bonus":           10,
                "score" :               5
        ]),
        ([      "quest":                "¥Ûƒ¡—Ú≈Æ",
                "quest_type":           "…±",
                "time":                 800,
                "exp_bonus":         100,
                "pot_bonus":           20,
                "score" :               5
        ]),
  ([      "quest":                "Õ‰µ∂",
                "quest_type":           "—∞",
                "time":                 800,
                "exp_bonus":       80,
                "pot_bonus":         20,
                "score" :               5
        ]),
       ([      "quest":                "∑…≥æ",
                "quest_type":           "…±",
                "time":                 200,
                "exp_bonus":          40,
                "pot_bonus":            10,
                "score" :               5
        ]),
       ([      "quest":                "◊Ø∂°",
                "quest_type":           "…±",
                "time":                 100,
                "exp_bonus":            50,
                "pot_bonus":           20,
                "score" :               5
        ]),
       ([      "quest":                "¬‰ª® Ã’ﬂ",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":           20,
                "score" :               5
        ]),
          ([      "quest":            "–°ƒ¡—Ú≈Æ",
                "quest_type":           "…±",
                "time":                 600,
                "exp_bonus":           50,
                "pot_bonus":            20,
                "score" :               5
        ]),
    ([      "quest":                "Õ∫”•",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":        50,
                "pot_bonus":          25,
                "score" :               20
        ]),
       ([      "quest":                "¿¥∏£",
                "quest_type":           "…±",
                "time":                 500,
                "exp_bonus":           50,
                "pot_bonus":           20,
                "score" :               5
        ]),
 ([      "quest":                "∫Ï…´…Æ≈€",
                "quest_type":           "—∞",
                "time":                 800,
                "exp_bonus":         80,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "ª∆“¬¿Æ¬Ô",
                "quest_type":           "…±",
                "time":                 800,
                "exp_bonus":         20,
                "pot_bonus":           10,
                "score" :               5
        ]),
        ([      "quest":                "ƒ¡—Úπ√ƒÔ",
                "quest_type":           "…±",
                "time":                 800,
                "exp_bonus":           100,
                "pot_bonus":           20,
                "score" :               5
        ]),
       ([      "quest":                "¥Ûƒ¡—Ú≈Æ",
                "quest_type":           "…±",
                "time":                 700,
                "exp_bonus":            100,
                "pot_bonus":           20,
                "score" :               5
        ]),       
        ([      "quest":                "¬‰ª®µ•µ∂",
                "quest_type":           "—∞",
                "time":                 300,
                "exp_bonus":         40,
                "pot_bonus":            20,
                "score" :               5
        ]),
      ([      "quest":                "œÙﬁ±Œ¢",
                "quest_type":           "…±",
                "time":                300,
                "exp_bonus":        50,
                "pot_bonus":         20,
                "score" :               5
        ]),
        ([      "quest":                "¿∂»Ô»Ô",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":         50,
                "pot_bonus":           20,
                "score" :               5
        ]),
 ([      "quest":                "øæ—ÚÕ»",
                "quest_type":           "—∞",
                "time":                 800,
                "exp_bonus":       80,
                "pot_bonus":         20,
                "score" :               5
        ]),
       ([      "quest":                "”ŒøÕ",
                "quest_type":           "…±",
                "time":                 150,
                "exp_bonus":         30,
                "pot_bonus":           10,
                "score" :               5
        ]),
        ([      "quest":                "∫Ï“¬¿Æ¬Ô",
                "quest_type":           "…±",
                "time":                 800,
                "exp_bonus":         20,
                "pot_bonus":           10,
                "score" :               5
        ]),
  ([      "quest":                "ıı∆§–°—•",
                "quest_type":           "—∞",
                "time":                400,
                "exp_bonus":       60,
                "pot_bonus":         20,
                "score" :              5
      ]),
       ([      "quest":                "…± ÷",
                "quest_type":           "…±",
                "time":                 400,
                "exp_bonus":          50,
                "pot_bonus":           20,
                "score" :              15
        ]),
    ([      "quest":                "…·¿˚◊”",
                "quest_type":          "—∞",
                "time":                 900,
                "exp_bonus":       100,
                "pot_bonus":         30,
                "score" :               5
        ]),
      ([      "quest":                "≤…ª®π√ƒÔ",
                "quest_type":           "…±",
                "time":                 200,
                "exp_bonus":          30,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "–°—Ú∏·",
                "quest_type":           "…±",
                "time":                 700,
                "exp_bonus":          50,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "–°√‡—Ú",
                "quest_type":           "…±",
                "time":                 800,
                "exp_bonus":          50,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "¥Û√‡—Ú",
                "quest_type":           "…±",
                "time":                 900,
                "exp_bonus":          50,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "¿º∏Û—æ˜ﬂ",
                "quest_type":           "…±",
                "time":                 500,
                "exp_bonus":          40,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "¿«π∑",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":          50,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "–°’≈",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":          30,
                "pot_bonus":           10,
                "score" :               5
        ]),
      ([      "quest":                "∞Ÿ±‰–«æ˝",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":          50,
                "pot_bonus":           20,
                "score" :               5
        ]),
    ([      "quest":                "«‡…´≥§≈€",
                "quest_type":          "—∞",
                "time":                 500,
                "exp_bonus":       30,
                "pot_bonus":         20,
                "score" :               5
        ]),
 ([      "quest":                "–°¿Æ¬Ô",
                "quest_type":           "…±",
                "time":                 500,
                "exp_bonus":         80,
                "pot_bonus":           20,
                "score" :               5
        ]),
   ([      "quest":                "ıı∆§Ã◊»π",
                "quest_type":           "—∞",
                "time":                 400,
                "exp_bonus":       60,
                "pot_bonus":         20,
                "score" :               5
        ]),
       ([      "quest":                "ÚﬂÚ—",
                "quest_type":           "…±",
                "time":                 200,
                "exp_bonus":           30,
                "pot_bonus":           10,
                "score" :               5
        ]),
      ([      "quest":                "≤®Àπ≈´",
                "quest_type":           "…±",
                "time":                 600,
                "exp_bonus":         80,
                "pot_bonus":           20,
                "score" :               5
        ]),
 ([      "quest":                "ΩπÈ‰Ω£",
                "quest_type":           "—∞",
                "time":                 400,
                "exp_bonus":       200,
                "pot_bonus":         20,
                "score" :               5
        ]),
       ([      "quest":                "÷–ƒÍ…Ã»À",
                "quest_type":           "…±",
                "time":                 800,
                "exp_bonus":         100,
                "pot_bonus":           30,
                "score" :               5
        ]),
         ([      "quest":                "ƒ¡—Ú±ﬁ",
                "quest_type":           "—∞",
                "time":                1000,
                "exp_bonus":       100,
                "pot_bonus":         30,
                "score" :              5
      ]),
  ([      "quest":                "—Ú√´»π",
                "quest_type":          "—∞",
                "time":                 800,
                "exp_bonus":       80,
                "pot_bonus":         20,
                "score" :               5
        ]),
    ([      "quest":                "ª∆…´…Æ≈€",
                "quest_type":          "—∞",
                "time":                 800,
                "exp_bonus":       80,
                "pot_bonus":         10,
                "score" :               5
        ]),
       ([      "quest":                "≤®Àπ≈´",
                "quest_type":           "…±",
                "time":                 700,
                "exp_bonus":          80,
                "pot_bonus":           20,
                "score" :               5
        ]),
    ([      "quest":                "ΩŸ∑À",
                "quest_type":           "…±",
                "time":                 300,
                "exp_bonus":          50,
                "pot_bonus":           20,
                "score" :               20
        ]),
        ([      "quest":                "≤ “¬…Ÿ≈Æ",
                "quest_type":           "…±",
                "time":              100,
                "exp_bonus":         40,
                "pot_bonus":           20,
                "score" :              5
        ]),
       ([      "quest":                "ø¥√≈≤Ó“€",
                "quest_type":           "…±",
                "time":                 100,
                "exp_bonus":         30,
                "pot_bonus":           10,
                "score" :            5
        ]),
        ([      "quest":                "¡¯ªÊ–ƒ",
                "quest_type":           "…±",
                "time":                 100,
                "exp_bonus":         40,
                "pot_bonus":           20,
                "score" :               5
        ]),
     ([      "quest":                "±±⁄§¥Û≈Ù",
                "quest_type":           "…±",
                "time":                 200,
                "exp_bonus":         50,
                "pot_bonus":          40,
                "score" :               20
        ]),
    ([      "quest":                "Ω“¯ª®…ﬂ",
                "quest_type":           "…±",
                "time":                 200,
                "exp_bonus":          50,
                "pot_bonus":           20,
                "score" :              5
        ]),
    ([      "quest":                "∑Ë¿œÕ∑◊”",
                "quest_type":           "…±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

