inherit SKILL;

mapping *quest = ({
        ([      "quest":                "ÆòØ¤",
                "quest_type":           "É±",
                "time":                 40,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "²ÃÒÂ¼ô",
                "quest_type":           "Ñ°",
                "time":                 120,
                "exp_bonus":            10,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "·è¹·",
                "quest_type":           "É±",
                "time":                 30,
                "exp_bonus":            15,
                "pot_bonus":            10,
                "score" :               20
        ]),
    ([      "quest":                "Á¿ÒÂ³ß",
                "quest_type":           "Ñ°",
                "time":                 60,
                "exp_bonus":            10,
                "pot_bonus":            10,
                "score" :               5
        ]),
         ([      "quest":                "×íºº",
                "quest_type":           "É±",
                "time":                 40,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
   ([      "quest":                "¼«ÀÖåÐÒ£É¢",
                "quest_type":           "Ñ°",
                "time":                 120,
                "exp_bonus":            10,
                "pot_bonus":            10,
                "score" :               5
        ]),
     ([      "quest":                "ÑòÆ¤¾Æ´ü",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":         20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "Å©·ò",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "¾ÉÊé",
                "quest_type":           "Ñ°",
                "time":                 50,
                "exp_bonus":            10,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "²ÝÐ¬",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "¶Å¿í",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            30,
                "pot_bonus":            10,
                "score" :               5
        ]),
      ([      "quest":                "ÃÛ·ä",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "ÊÕÆÆÀÃµÄ",
                "quest_type":           "É±",
                "time":                 40,
                "exp_bonus":          10,
                "pot_bonus":           5,
                "score" :               5
        ]),
       ([      "quest":                "ÍõÌú½³",
                "quest_type":           "É±",
                "time":                 40,
                "exp_bonus":           20,
                "pot_bonus":            10,
                "score" :               5
        ]),
       ([      "quest":                "ÎºÎÞ¼«",
                "quest_type":           "É±",
                "time":                 30,
                "exp_bonus":            10,
                "pot_bonus":            10,
                "score" :               5
        ]),
       ([      "quest":                "Îä¹ÝµÜ×Ó",
                "quest_type":           "É±",
                "time":                 40,
                "exp_bonus":            10,
                "pot_bonus":            10,
                "score" :               5
        ]),
       ([      "quest":                "éÔ·ò",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":          20,
                "pot_bonus":           10,
                "score" :               5
        ]),
     ([      "quest":                "Ìú´¸",
                "quest_type":           "Ñ°",
                "time":                 50,
                "exp_bonus":       20,
                "pot_bonus":         15,
                "score" :               5
        ]),
        ([      "quest":                "±¦¹Ù",
                "quest_type":           "É±",
                "time":                 80,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               5
        ]),
      ([      "quest":                "Æ¤ÒÂ",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
     ([      "quest":                "ºÚÉ«É®ÅÛ",
                "quest_type":          "Ñ°",
                "time":                 800,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
       ([      "quest":                "ð±Ä¸",
                "quest_type":           "É±",
                "time":                 50,
                "exp_bonus":           20,
                "pot_bonus":            10,
                "score" :               5
        ]),
      ([      "quest":                "¶Ì½£",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
        ([      "quest":                "ÍÁ·ËÐ¡à¶ÂÞ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":         30,
                "pot_bonus":           10,
                "score" :               10
        ]),
      ([      "quest":                "¿¾ÑòÍÈ",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
       ([      "quest":                "ÍÁ·Ëà¶ÂÞ",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         80,
                "pot_bonus":           30,
                "score" :               10
        ]),
       ([      "quest":                "Ìú¸«",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":         20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "Ð¡ÍçÍ¯",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         20,
                "pot_bonus":           10,
                "score" :               5
        ]),
       ([      "quest":                "ÄÁÑò±Þ",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":         20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "»ÆÒÂÀ®Âï",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":         20,
                "pot_bonus":           10,
                "score" :               5
        ]),
       ([      "quest":                "ÑîÕÆ¹ñ",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         20,
                "pot_bonus":           10,
                "score" :               5
        ]),
     ([      "quest":                "»ÆÉ«É®ÅÛ",
                "quest_type":          "Ñ°",
                "time":                 800,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
       ([      "quest":                "Àî»ðÊ¨",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":          20,
                "pot_bonus":            10,
                "score" :               5
        ]),
         ([      "quest":                "·ÉïÚ",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
       ([      "quest":                "½©Ê¬ÊÌÕß",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":          30,
                "pot_bonus":            10,
                "score" :               5
        ]),
       ([      "quest":                "ÂÃ¿Í",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":         20,
                "pot_bonus":           15,
                "score" :               5
        ]),
 ([      "quest":                "½¹éä½£",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
       ([      "quest":                "²Ã·ì",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":           20,
                "pot_bonus":            10,
                "score" :               5
        ]),
  ([      "quest":                "Ð¡À®Âï",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":         30,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "·ûÖä¼ò½é",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :              5
      ]),
       ([      "quest":                "²è¹¤",
                "quest_type":           "É±",
                "time":                 40,
                "exp_bonus":         20,
                "pot_bonus":           10,
                "score" :               5
        ]),
    ([      "quest":                "Ä§·¨ÈëÃÅ",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :              5
      ]),
       ([      "quest":                "ÔÓ»õ··",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":         30,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "¹ýÕÐÒªÖ¼",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
     ([      "quest":                "Ð¡»¨Í¯",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         30,
                "pot_bonus":           20,
                "score" :               5
        ]),
   ([      "quest":                "ÁÖÈýÒ¯",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":         20,
                "pot_bonus":           10,
                "score" :               5
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

