inherit SKILL;

mapping *quest = ({
        ([      "quest":                "ºÚ¹Ú¾Þòþ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":         60,
                "pot_bonus":          30,
                "score" :               5
        ]),
     ([      "quest":                "ºúµ¶",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":       100,
                "pot_bonus":         30,
                "score" :               5
        ]),
    ([      "quest":                "ÍÁ·ËÀÏ´ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":         40,
                "pot_bonus":           20,
                "score" :               10
        ]),
   ([      "quest":                "ÑòÆ¤¾Æ´ü",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":         50,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "³¤°×»¢",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         200,
                "pot_bonus":           30,
                "score" :               20
        ]),
     ([      "quest":                "ºÚÉ«É®ÅÛ",
                "quest_type":          "Ñ°",
                "time":                 800,
                "exp_bonus":       50,
                "pot_bonus":         10,
                "score" :               5
        ]),
      ([      "quest":                "×¯Ô°»¨½³",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":            30,
                "pot_bonus":           10,
                "score" :               5
        ]),
         ([      "quest":                "Ñ¾÷ß",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":          30,
                "pot_bonus":           10,
                "score" :               5
        ]),
        ([      "quest":                "Âô»¨¹ÃÄï",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":         30,
                "pot_bonus":           10,
                "score" :               5
        ]),
  ([      "quest":                "ºÚÐÜ",
                "quest_type":         "É±",
                "time":                 100,
                "exp_bonus":       30,
                "pot_bonus":         10,
                "score" :               5
        ]),
       ([      "quest":                "ÌË×ÓÊÖ",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":          30,
                "pot_bonus":            10,
                "score" :               5
        ]),
       ([      "quest":                "±øÆ÷··×Ó",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            50,
                "pot_bonus":           20,
                "score" :               5
        ]),
       ([      "quest":                "½©Ê¬»¤·¨",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":           20,
                "score" :               5
        ]),
          ([      "quest":                "Ð¡ÄÁÑòÅ®",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":           50,
                "pot_bonus":            20,
                "score" :               5
        ]),
    ([      "quest":                "ÍºÓ¥",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":        50,
                "pot_bonus":          25,
                "score" :               20
        ]),
       ([      "quest":                "ÅËÈôÇï",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":           30,
                "pot_bonus":           10,
                "score" :               5
        ]),
 ([      "quest":                "ºìÉ«É®ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":         80,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "»ÆÒÂÀ®Âï",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":         80,
                "pot_bonus":           20,
                "score" :               5
        ]),
        ([      "quest":                "´¬·ò",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":           30,
                "pot_bonus":           10,
                "score" :               5
        ]),
       ([      "quest":                "Áõ°²Â»",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":            50,
                "pot_bonus":           10,
                "score" :               5
        ]),       
        ([      "quest":                "É®¹÷",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":         20,
                "pot_bonus":            10,
                "score" :               5
        ]),
      ([      "quest":                "»¤ËÂÎäÉ®",
                "quest_type":           "É±",
                "time":                100,
                "exp_bonus":        30,
                "pot_bonus":         10,
                "score" :               5
        ]),
        ([      "quest":                "Öª¿ÍÉ®",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":         30,
                "pot_bonus":           10,
                "score" :               5
        ]),
 ([      "quest":                "¿¾ÑòÍÈ",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":       50,
                "pot_bonus":         20,
                "score" :               5
        ]),
       ([      "quest":                "»¯ÔµºÍÉÐ",
                "quest_type":           "É±",
                "time":                 150,
                "exp_bonus":         30,
                "pot_bonus":           10,
                "score" :               5
        ]),
        ([      "quest":                "ºìÒÂÀ®Âï",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":         120,
                "pot_bonus":           20,
                "score" :               5
        ]),
  ([      "quest":                "Ä§·¨ÈëÃÅ",
                "quest_type":           "Ñ°",
                "time":                100,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :              5
      ]),
       ([      "quest":                "É±ÊÖ",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":          50,
                "pot_bonus":           20,
                "score" :              15
        ]),
    ([      "quest":                "²ÐÆÆµ¶Æ×",
                "quest_type":          "Ñ°",
                "time":                 500,
                "exp_bonus":       30,
                "pot_bonus":         15,
                "score" :               5
        ]),
      ([      "quest":                "ÎüÑªòùòð",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":          30,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "Ð¡Ñò¸á",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":          50,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "Ð¡ÃàÑò",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":          50,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "´óÃàÑò",
                "quest_type":           "É±",
                "time":                 900,
                "exp_bonus":          50,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "À¼¸óÑ¾÷ß",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":          40,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "ÀÇ¹·",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":          50,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "Ð¡ÕÅ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":          30,
                "pot_bonus":           10,
                "score" :               5
        ]),
      ([      "quest":                "°Ù±äÐÇ¾ý",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":          50,
                "pot_bonus":           20,
                "score" :               5
        ]),
    ([      "quest":                "ÇàÉ«³¤ÅÛ",
                "quest_type":          "Ñ°",
                "time":                 500,
                "exp_bonus":       30,
                "pot_bonus":         20,
                "score" :               5
        ]),
 ([      "quest":                "Ð¡À®Âï",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         80,
                "pot_bonus":           20,
                "score" :               5
        ]),
   ([      "quest":                "¹ýÕÐÒªÖ¼",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
       ([      "quest":                "ÕÑÒÇ",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":           30,
                "pot_bonus":           10,
                "score" :               5
        ]),
      ([      "quest":                "²¨Ë¹Å«",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":         60,
                "pot_bonus":           20,
                "score" :               5
        ]),
 ([      "quest":                "½¹éä½£",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":       200,
                "pot_bonus":         20,
                "score" :               5
        ]),
       ([      "quest":                "ÖÐÄêÉÌÈË",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":         70,
                "pot_bonus":           30,
                "score" :               5
        ]),
         ([      "quest":                "ÄÁÑò±Þ",
                "quest_type":           "Ñ°",
                "time":                1000,
                "exp_bonus":       100,
                "pot_bonus":         30,
                "score" :              5
      ]),
  ([      "quest":                "ÑòÃ«È¹",
                "quest_type":          "Ñ°",
                "time":                 800,
                "exp_bonus":       80,
                "pot_bonus":         20,
                "score" :               5
        ]),
       ([      "quest":                "·¼ç±",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":          30,
                "pot_bonus":           10,
                "score" :               5
        ]),
    ([      "quest":                "»ÆÉ«É®ÅÛ",
                "quest_type":          "Ñ°",
                "time":                 800,
                "exp_bonus":       60,
                "pot_bonus":         10,
                "score" :               5
        ]),
       ([      "quest":                "²¨Ë¹Å«",
                "quest_type":           "É±",
                "time":                 700,
                "exp_bonus":          50,
                "pot_bonus":           20,
                "score" :               5
        ]),
    ([      "quest":                "½Ù·Ë",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":          50,
                "pot_bonus":           20,
                "score" :               20
        ]),
        ([      "quest":                "²ÊÒÂÉÙÅ®",
                "quest_type":           "É±",
                "time":              400,
                "exp_bonus":         40,
                "pot_bonus":           20,
                "score" :              5
        ]),
     ([      "quest":                "ÞÄÕß",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":         30,
                "pot_bonus":           15,
                "score" :             5
        ]),
     ([      "quest":                "Ö£ÍÀ·ò",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":         40,
                "pot_bonus":           20,
                "score" :            5
        ]),
     ([      "quest":                "¿´ÃÅ²îÒÛ",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":         30,
                "pot_bonus":           10,
                "score" :            5
        ]),
       ([      "quest":                "·ÉÔô",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":         40,
                "pot_bonus":           20,
                "score" :               10
        ]),
        ([      "quest":                "Áø»æÐÄ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":         40,
                "pot_bonus":           20,
                "score" :               5
        ]),
     ([      "quest":                "±±Ú¤´óÅô",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         50,
                "pot_bonus":          40,
                "score" :               20
        ]),
     ([      "quest":                "·èÀÏÍ·×Ó",
                "quest_type":           "É±",
                "time":               300,
                "exp_bonus":         60,
                "pot_bonus":         25,
                "score" :             5
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}


