inherit SKILL;

mapping *quest = ({
        ([      "quest":                "ÀÏÄêÉÌÈË",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         200,
                "pot_bonus":          30,
                "score" :               5
        ]),
      ([      "quest":                "×ÏÉ«Éñ¾ý",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":           200,
                "pot_bonus":           30,
                "score" :               5
        ]),
     ([      "quest":                "»ÆÉ«Éñ¾ý",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         250,
                "pot_bonus":          20,
                "score" :               5
        ]),
     ([      "quest":                "Ðå»¨Ð¡Ð¬",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":       120,
                "pot_bonus":         20,
                "score" :               5
        ]),
     ([      "quest":                "ºúµ¶",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":       240,
                "pot_bonus":         30,
                "score" :               5
        ]),
    ([      "quest":                "ÄêÇáÉÌÈË",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":       200,
                "pot_bonus":           30,
                "score" :               5
        ]),
   ([      "quest":                "ÑòÆ¤¾Æ´ü",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":         270,
                "pot_bonus":            30,
                "score" :               5
        ]),
        ([      "quest":                "³¤°×»¢",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         300,
                "pot_bonus":           30,
                "score" :               5
        ]),
     ([      "quest":                "ºÚÉ«É®ÅÛ",
                "quest_type":          "Ñ°",
                "time":                 800,
                "exp_bonus":       230,
                "pot_bonus":        20,
                "score" :               5
        ]),
      ([      "quest":                "³àÉ«Éñ¾ý",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":         200,
                "pot_bonus":           30,
                "score" :               5
        ]),
     ([      "quest":                "ÇàÉ«Éñ¾ý",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":          200,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "´óÄÁÑòÅ®",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":         200,
                "pot_bonus":           30,
                "score" :               5
        ]),
  ([      "quest":                "Íäµ¶",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":       280,
                "pot_bonus":        30,
                "score" :               5
        ]),
       ([      "quest":                "ÂÌÉ«Éñ¾ý",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":       200,
                "pot_bonus":         30,
                "score" :               5
        ]),
       ([      "quest":                "¼ÒÅ«",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":        200,
                "pot_bonus":           20,
                "score" :               5
        ]),
          ([      "quest":            "Ð¡ÄÁÑòÅ®",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         200,
                "pot_bonus":            20,
                "score" :               5
        ]),
    ([      "quest":                "ÍºÓ¥",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":        170,
                "pot_bonus":          25,
                "score" :               20
        ]),
 ([      "quest":                "ºìÉ«É®ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":         280,
                "pot_bonus":           30,
                "score" :               5
        ]),
        ([      "quest":                "»ÆÒÂÀ®Âï",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":         200,
                "pot_bonus":           20,
                "score" :               5
        ]),
        ([      "quest":                "ÄÁÑò¹ÃÄï",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":         200,
                "pot_bonus":           20,
                "score" :               5
        ]),
       ([      "quest":                "´óÄÁÑòÅ®",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":         280,
                "pot_bonus":           20,
                "score" :               5
        ]),       
        ([      "quest":                "Âä»¨µ¥µ¶",
                "quest_type":           "Ñ°",
                "time":                 180,
                "exp_bonus":         180,
                "pot_bonus":            20,
                "score" :               5
        ]),
      ([      "quest":                "ÏôÞ±Î¢",
                "quest_type":           "É±",
                "time":                100,
                "exp_bonus":       150,
                "pot_bonus":         20,
                "score" :               5
        ]),
        ([      "quest":                "À¶ÈïÈï",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":         150,
                "pot_bonus":           20,
                "score" :               5
        ]),
 ([      "quest":                "¿¾ÑòÍÈ",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":       240,
                "pot_bonus":         20,
                "score" :               5
        ]),
        ([      "quest":                "ºìÒÂÀ®Âï",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":         200,
                "pot_bonus":           20,
                "score" :               5
        ]),
  ([      "quest":                "õõÆ¤Ð¡Ñ¥",
                "quest_type":           "Ñ°",
                "time":                200,
                "exp_bonus":       160,
                "pot_bonus":         20,
                "score" :              5
      ]),
    ([      "quest":                "ÉáÀû×Ó",
                "quest_type":          "Ñ°",
                "time":                 800,
                "exp_bonus":       200,
                "pot_bonus":         30,
                "score" :               5
        ]),
      ([      "quest":                "Ð¡Ñò¸á",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":         180,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "Ð¡ÃàÑò",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":         180,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "´óÃàÑò",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":          180,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "´Ö²¼ºÚÅÛ",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":         180,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "´Ö²¼°×ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":          180,
                "pot_bonus":           20,
                "score" :               5
        ]),
([      "quest":                "°²Ï§åÇ",
                "quest_type":           "É±",
                "time":                 900,
                "exp_bonus":       300,
                "pot_bonus":           30,
                "score" :               5
        ]),
      ([      "quest":                "°Ù±äÐÇ¾ý",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":         150,
                "pot_bonus":           20,
                "score" :               5
        ]),
    ([      "quest":                "ÇàÉ«³¤ÅÛ",
                "quest_type":          "Ñ°",
                "time":                 200,
                "exp_bonus":       130,
                "pot_bonus":         20,
                "score" :               5
        ]),
 ([      "quest":                "Ð¡À®Âï",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         200,
                "pot_bonus":           20,
                "score" :               5
        ]),
   ([      "quest":                "õõÆ¤Ì×È¹",
                "quest_type":           "Ñ°",
                "time":                200,
                "exp_bonus":       160,
                "pot_bonus":         20,
                "score" :               5
        ]),
       ([      "quest":                "ºÚ²¼ÅÛ",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":         180,
                "pot_bonus":           20,
                "score" :               5
        ]),
      ([      "quest":                "²¨Ë¹Å«",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         200,
                "pot_bonus":           20,
                "score" :               5
        ]),
 ([      "quest":                "½¹éä½£",
                "quest_type":           "Ñ°",
                "time":                 400,
                "exp_bonus":       300,
                "pot_bonus":         20,
                "score" :               5
        ]),
       ([      "quest":                "ÖÐÄêÉÌÈË",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":         200,
                "pot_bonus":           30,
                "score" :               5
        ]),
         ([      "quest":                "ÄÁÑò±Þ",
                "quest_type":           "Ñ°",
                "time":                700,
                "exp_bonus":       200,
                "pot_bonus":         30,
                "score" :              5
      ]),
  ([      "quest":                "ÑòÃ«È¹",
                "quest_type":          "Ñ°",
                "time":                 700,
                "exp_bonus":       280,
                "pot_bonus":         20,
                "score" :               5
        ]),
    ([      "quest":                "»ÆÉ«É®ÅÛ",
                "quest_type":          "Ñ°",
                "time":                 700,
                "exp_bonus":       200,
                "pot_bonus":         20,
                "score" :               5
        ]),
       ([      "quest":                "²¨Ë¹Å«",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":         200,
                "pot_bonus":           20,
                "score" :               5
        ]),
    ([      "quest":                "Ä½ÈÝ·å",
                "quest_type":           "É±",
                "time":                 400,
                "exp_bonus":       200,
                "pot_bonus":           30,
                "score" :               20
        ]),
        ([      "quest":                "Ð¡·ï",
                "quest_type":           "É±",
                "time":              400,
                "exp_bonus":         200,
                "pot_bonus":           30,
                "score" :              5
        ]),
           ([      "quest":                "Áø»æÐÄ",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":         140,
                "pot_bonus":           20,
                "score" :               5
        ]),
       ([      "quest":                "³Â½£Çï",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         200,
                "pot_bonus":          40,
                "score" :               20
        ]),
    ([      "quest":                "Ã½ÆÅ",
                "quest_type":           "É±",
                "time":               500,
                "exp_bonus":         260,
                "pot_bonus":         25,
                "score" :             5
        ]),
  ([      "quest":                "ÏØ³Ç¹Ù±ø",
                "quest_type":           "É±",
                "time":               400,
                "exp_bonus":         400,
                "pot_bonus":          40,
                "score" :               30
        ]),
  ([      "quest":                "ÎÞÃûÀÏ¸¾",
                "quest_type":           "É±",
                "time":              400,
                "exp_bonus":         200,
                "pot_bonus":          30,
                "score" :               20
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

