inherit SKILL;

mapping *quest = ({
        ([      "quest":                "ÃÅ·¿",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":         40,
                "pot_bonus":          10,
                "score" :               5
        ]),
     ([      "quest":                "Æ¤ÒÂ",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
    ([      "quest":                "ÍÁ·ËÀÏ´ó",
                "quest_type":           "É±",
                "time":                 500,
                "exp_bonus":         40,
                "pot_bonus":           20,
                "score" :               10
        ]),
   ([      "quest":                "ÑòÆ¤¾Æ´ü",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":         20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "ð±Ä¸",
                "quest_type":           "É±",
                "time":                 50,
                "exp_bonus":         20,
                "pot_bonus":           10,
                "score" :               5
        ]),
        ([      "quest":                "ÍÁ·Ëà¶ÂÞ",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":         40,
                "pot_bonus":           20,
                "score" :               20
        ]),
     ([      "quest":                "ºÚÉ«É®ÅÛ",
                "quest_type":          "Ñ°",
                "time":                 800,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
      ([      "quest":                "Ð¡ÍçÍ¯",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            20,
                "pot_bonus":           10,
                "score" :               5
        ]),
         ([      "quest":                "ºÚÒÂÈË",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":          30,
                "pot_bonus":           10,
                "score" :               5
        ]),
        ([      "quest":                "Âô»¨¹ÃÄï",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":         20,
                "pot_bonus":           10,
                "score" :               5
        ]),
  ([      "quest":                "¶Ì½£",
                "quest_type":           "Ñ°",
                "time":                 200,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
       ([      "quest":                "ÑîÕÆ¹ñ",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":          20,
                "pot_bonus":            10,
                "score" :               5
        ]),
       ([      "quest":                "Àî»ðÊ¨",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":         20,
                "pot_bonus":            10,
                "score" :               5
        ]),
       ([      "quest":                "½©Ê¬ÊÌÕß",
                "quest_type":           "É±",
                "time":                 100,
                "exp_bonus":            30,
                "pot_bonus":           10,
                "score" :               5
        ]),
       ([      "quest":                "ÂÃ¿Í",
                "quest_type":           "É±",
                "time":                 50,
                "exp_bonus":           20,
                "pot_bonus":            10,
                "score" :               5
        ]),
    ([      "quest":                "ÎÔÁú¸ÚÇ¿µÁ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":        40,
                "pot_bonus":          15,
                "score" :               20
        ]),
       ([      "quest":                "ÅËÈôÇï",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":           30,
                "pot_bonus":           10,
                "score" :               5
        ]),
 ([      "quest":                "ÄÁÑò±Þ",
                "quest_type":           "Ñ°",
                "time":                 800,
                "exp_bonus":         20,
                "pot_bonus":            10,
                "score" :               5
        ]),
        ([      "quest":                "»ÆÒÂÀ®Âï",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":         20,
                "pot_bonus":           10,
                "score" :               5
        ]),
        ([      "quest":                "´¬·ò",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":           30,
                "pot_bonus":           10,
                "score" :               5
        ]),
       ([      "quest":                "Áõ°²Â»",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":            50,
                "pot_bonus":           10,
                "score" :               5
        ]),       ([      "quest":                "É®¹÷",
                "quest_type":           "Ñ°",
                "time":                 300,
                "exp_bonus":         20,
                "pot_bonus":            10,
                "score" :               5
        ]),
      ([      "quest":                "»¤ËÂÎäÉ®",
                "quest_type":           "É±",
                "time":                150,
                "exp_bonus":        20,
                "pot_bonus":         10,
                "score" :               5
        ]),
        ([      "quest":                "Öª¿ÍÉ®",
                "quest_type":           "É±",
                "time":                 250,
                "exp_bonus":         30,
                "pot_bonus":           10,
                "score" :               5
        ]),
 ([      "quest":                "¿¾ÑòÍÈ",
                "quest_type":           "Ñ°",
                "time":                 600,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
       ([      "quest":                "»¯ÔµºÍÉÐ",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":         30,
                "pot_bonus":           10,
                "score" :               5
        ]),
        ([      "quest":                "ºìÒÂÀ®Âï",
                "quest_type":           "É±",
                "time":                 800,
                "exp_bonus":         20,
                "pot_bonus":           10,
                "score" :               5
        ]),
  ([      "quest":                "Ä§·¨ÈëÃÅ",
                "quest_type":           "Ñ°",
                "time":                300,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :              5
      ]),
       ([      "quest":                "É±ÊÖ",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":          20,
                "pot_bonus":           10,
                "score" :               5
        ]),
    ([      "quest":                "²ÐÆÆµ¶Æ×",
                "quest_type":          "Ñ°",
                "time":                 600,
                "exp_bonus":       30,
                "pot_bonus":         15,
                "score" :               5
        ]),
      ([      "quest":                "ÎüÑªòùòð",
                "quest_type":           "É±",
                "time":                 120,
                "exp_bonus":          20,
                "pot_bonus":           10,
                "score" :               5
        ]),
   ([      "quest":                "ºìÉ«É®ÅÛ",
                "quest_type":          "Ñ°",
                "time":                 800,
                "exp_bonus":       30,
                "pot_bonus":         20,
                "score" :               5
        ]),
 ([      "quest":                "Ð¡À®Âï",
                "quest_type":           "É±",
                "time":                 600,
                "exp_bonus":         30,
                "pot_bonus":           20,
                "score" :               5
        ]),
   ([      "quest":                "¹ýÕÐÒªÖ¼",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
       ([      "quest":                "ÕÑÒÇ",
                "quest_type":           "É±",
                "time":                 200,
                "exp_bonus":           30,
                "pot_bonus":           10,
                "score" :               5
        ]),
 ([      "quest":                "½¹éä½£",
                "quest_type":           "Ñ°",
                "time":                 500,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
         ([      "quest":                "·ûÖä¼ò½é",
                "quest_type":           "Ñ°",
                "time":                200,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :              5
      ]),
  ([      "quest":                "Â¹Æ¤Ð¡Ñ¥",
                "quest_type":          "Ñ°",
                "time":                 200,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
       ([      "quest":                "·¼ç±",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":          30,
                "pot_bonus":           10,
                "score" :               5
        ]),
    ([      "quest":                "»ÆÉ«É®ÅÛ",
                "quest_type":          "Ñ°",
                "time":                 800,
                "exp_bonus":       20,
                "pot_bonus":         10,
                "score" :               5
        ]),
       ([      "quest":                "Çúð¥ç÷",
                "quest_type":           "É±",
                "time":                 300,
                "exp_bonus":          20,
                "pot_bonus":           10,
                "score" :               5
        ]),
     });

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
